[[plugins]]
repo = 'Shougo/unite.vim'
on_event = 'BufRead'
hook_add = '''
  let g:unite_enable_start_insert=1
  if executable('pt')
    let g:unite_source_grep_command = 'pt'
    let g:unite_source_grep_default_opts = '--nogroup --nocolor'
    let g:unite_source_grep_recursive_opt = ''
    let g:unite_source_grep_encoding = 'utf-8'
  endif
  nnoremap <silent> ,b :<C-u>Unite buffer<CR>
  nnoremap <silent> ,f :<C-u>Unite file<CR>
  nnoremap <silent> ,c :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
  nnoremap <silent> ,g  :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
'''

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_ft = ['unite']
